spring:
  datasource:
    username: root
    password: mysqladmin
    url: jdbc:mysql://localhost:3306/spring-cache
    driver-class-name: com.mysql.jdbc.Driver
#配置连接主机的ip
  redis:
    host: 192.168.184.66
#开启驼峰命名式
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#查看日志信息
logging:
  level: com.kyle.cache.mapper=debug


